# Generated by Django 5.0.3 on 2024-03-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TOEICScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_code', models.CharField(max_length=255)),
                ('institution_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255)),
                ('administration_number', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('test_date', models.DateField()),
                ('l_score', models.IntegerField()),
                ('l_percentile_rank', models.IntegerField()),
                ('r_score', models.IntegerField()),
                ('r_percentile_rank', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('l_abilities_measured_1_percentage', models.IntegerField(blank=True, null=True)),
                ('l_abilities_measured_1_average', models.IntegerField(blank=True, null=True)),
                ('l_abilities_measured_2_percentage', models.IntegerField(blank=True, null=True)),
                ('l_abilities_measured_2_average', models.IntegerField(blank=True, null=True)),
                ('l_abilities_measured_3_percentage', models.IntegerField(blank=True, null=True)),
                ('l_abilities_measured_3_average', models.IntegerField(blank=True, null=True)),
                ('l_abilities_measured_4_percentage', models.IntegerField(blank=True, null=True)),
                ('l_abilities_measured_4_average', models.IntegerField(blank=True, null=True)),
                ('l_abilities_measured_5_percentage', models.IntegerField(blank=True, null=True)),
                ('l_abilities_measured_5_average', models.IntegerField(blank=True, null=True)),
                ('r_abilities_measured_1_percentage', models.IntegerField(blank=True, null=True)),
                ('r_abilities_measured_1_average', models.IntegerField(blank=True, null=True)),
                ('r_abilities_measured_2_percentage', models.IntegerField(blank=True, null=True)),
                ('r_abilities_measured_2_average', models.IntegerField(blank=True, null=True)),
                ('r_abilities_measured_3_percentage', models.IntegerField(blank=True, null=True)),
                ('r_abilities_measured_3_average', models.IntegerField(blank=True, null=True)),
                ('r_abilities_measured_4_percentage', models.IntegerField(blank=True, null=True)),
                ('r_abilities_measured_4_average', models.IntegerField(blank=True, null=True)),
                ('r_abilities_measured_5_percentage', models.IntegerField(blank=True, null=True)),
                ('r_abilities_measured_5_average', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
