# Generated by Django 5.0.3 on 2024-03-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toeicscore',
            name='administration_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='toeicscore',
            name='institution_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='toeicscore',
            name='institution_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='toeicscore',
            name='registration_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
